//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corredores
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corredor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Corredor()
        {
            this.TiemposCorredors = new HashSet<TiemposCorredor>();
        }
    
        public int CorredorID { get; set; }
        public string CorredorNombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TiemposCorredor> TiemposCorredors { get; set; }
    }
}
