//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corredores
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiemposCorredor
    {
        public int TiemposCorredorID { get; set; }
        public Nullable<int> CorredorID { get; set; }
        public int Minutos { get; set; }
        public int Segundos { get; set; }
    
        public virtual Corredor Corredor { get; set; }
    }
}
