//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corredores.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Corredor
    {
        public int CorredorID { get; set; }

        [Required]
        public string CorredorNombre { get; set; }
        public Nullable<int> Minutos { get; set; }
        public Nullable<int> Segundos { get; set; }
    }
}
